### ISSUE TITLE
Unable to see the test selected in live unit test and option selected for git branch

### ISSUE THREAD

**Issue by mddheeraj** [catppuccin/visual-studio#4]
Hello. 

We have seen two issues.
1. We are unable to see the test selected in live unit test.
2. when we right click on git branch and unable to select or can't see which option I have selected, we use mouse for selecting one of the option.
![mouseoverandselectionscan'tsee](https://user-images.githubusercontent.com/20344363/232130865-75b9dbe6-e774-4a9e-b236-81bbec69c096.png)

**Comment by djflan** [comment]
Please change to default dark theme and show the same screenshot. I need to be able to see what should be there if I am to reproduce and fix.

**Comment by mddheeraj** [comment]
screenshot below in dark default visual studio theme.
![darktheme-mouseoverandselectionscansee](https://user-images.githubusercontent.com/20344363/232171203-c058e87c-6d4a-433e-ad4d-12e9e7751033.png)

**Comment by djflan** [comment]
@mddheeraj Please test in v1.1.0 - I believe this might have been fixed, if not, will keep looking

**Comment by mddheeraj** [comment]
I still don't see after I update to v1.1.0
![mouseoverselectioncan'tsee](https://user-images.githubusercontent.com/20344363/232539701-d3819a31-e05f-45b2-8a57-4288c47aebe6.png)

**Comment by djflan** [comment]
@mddheeraj ok, thanks - I'll need to continue to look into it.

**Comment by djflan** [comment]
@mddheeraj Please try v1.2.0 - I believe I have fixed this (the text color when disabled is still an issue)

**Comment by mddheeraj** [comment]
Thanks for the update will update and check.
